version: "3"


services:
  app:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - example-volume:/example_dir
    tty: true
    networks:
      - frontend
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Tokyo
    restart: always
    networks:
    - frontend
    - backend
    volumes:
    - mysql_data:/var/lib/mysql
    # Health check to start application server after database startup check
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 100

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24

volumes:
  example-volume:
    name: sample-volume-name
    driver: local
