version: "3"


services:
  app:
    build:
      image: sample-image-name
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/src
      - example-volume:/example_dir
    tty: true

volumes:
  example-volume:
    name: sample-volume-name
