version: "3"


services:
  app:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - example-volume:/example_dir
    tty: true

volumes:
  example-volume:
    name: sample-volume-name
