version: "3"


services:
  app:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/src
      - example-volume:/example_dir
    tty: true
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24

volumes:
  example-volume:
    name: sample-volume-name
